### ISSUE TITLE
Readme file need to be  changed, Missing mode = "wb"

### ISSUE THREAD

**Issue by joyliujoyliu** [mhpob/otndo#40]
![image](https://github.com/mhpob/otndo/assets/113057199/b6a986bf-0b6e-4c6a-b1aa-317f78bd6a44)

Missing mode = "wb" 

https://github.com/mhpob/otndo/blob/main/R/make_tag_push_summary.R#L24 use the function's example for now

**Comment by mhpob** [comment]
Closed by 72feefa707e2e3c7d5aec36f34856e15a3125be4
